blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('post/<slug:slugInput>/', views.detailPost, name="detail"),
    path('category/<slug:categoryInput>/', views.categoryPost, name="category"),
    path('contact/', views.kontak, name="contact"),
]

app_name = 'blog'

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.

class Post(models.Model):
    judul       = models.CharField(max_length=255)
    body        = models.TextField()
    category    = models.CharField(max_length=255)
    publish_time= models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(blank=True, editable= False)

    def save(self):
        self.slug = slugify(self.judul)
        super(Post, self).save()

    def __str__(self):
        return '{}. {}'.format(self.id, self.judul)
    

blog/forms.py
from django import forms

class ContactForm(forms.Form):
    nama_lengkap    = forms.CharField(
        label='Nama Lengkap',
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Nama Lengkap Anda',
            }
        )
    )
    jenis_kelamin   = forms.ChoiceField(
        choices= [
            ('P', 'Pria'),
            ('W', 'Wanita'),
        ],
        widget= forms.RadioSelect(
            attrs={
                'class':'form-check-input',
            }
        ),
    )
    tanggal_lahir   = forms.DateField(
        widget=forms.SelectDateWidget(
            years=range(1945,2021),
            attrs={
                'class':'form-control col-sm-2',
            }
        )
    )
    email           = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Email anda',
            }
        ),
    )
    alamat          = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
            }
        )
    )
    agree           = forms.BooleanField(
        widget=forms.CheckboxInput(
            attrs={
                'class':'form-check-input',
            }
        )
    )

blog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Post

from .forms import ContactForm

def index(request):
    posts = Post.objects.all()
    categories = Post.objects.values('category').distinct()
    context = {
        'Judul':'Home Blog',
        'Content':'Ini adalah halaman blog!',
        'Posts':posts,
        'Categories':categories,
    }

    return render(request, 'blog/index.html', context)

def detailPost(request, slugInput):
    posts = Post.objects.get(slug=slugInput)
    context = {
        'Judul':'Home Blog',
        'Content':'Ini adalah halaman blog!',
        'DetailPost':posts,
    }

    return render(request, 'blog/detail.html', context)

def categoryPost(request, categoryInput):
    posts = Post.objects.filter(category=categoryInput)

    categories = Post.objects.values('category').distinct()

    context = {
        'Judul':'Home Blog',
        'Content':'Tampilkan berdasarkan category',
        'Posts':posts,
        'Categories':categories,
    }

    return render(request, 'blog/category.html', context)

def kontak(request):
    contact_form = ContactForm()
    context = {
        'Judul':'Kontak',
        'Content':'Kontak Saya',
        'data_form':contact_form,
    }

    print(request.POST)

    return render(request, 'blog/contact.html', context)

mywebsite/views.py
from django.shortcuts import render

def index(request):
    context = {
        'Judul':'Home Page',
        'Content':'Ini adalah homepage dari website ini!',
    }
    return render(request, 'index.html', context)

blog/templates/blog/category.html
{% extends 'base.html' %}

{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}
    {{Content}}

    <br>

        {% for category in Categories %}
            <a href="/blog/category/{{category.category}}" role="button">{{category.category}}</a>
        {% endfor %}
            <a href="/blog" role="button">All Post</a>


    {% for post in Posts %}
        <a href="/blog/post/{{post.slug}}">
        <h1>{{post.judul}}</h1>
        </a>
        <p>{{post.publish_time}}</p>
        <p>{{post.body|truncatechars:200}}</p>
    {% endfor %}
    

{% endblock contents %}

blog/templates/blog/contact.html
{% extends 'base.html' %}

{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}
    {{Content}}

    <form method="post">
    {% csrf_token %}
        <div class="form-group">
            {{data_form.nama_lengkap.label_tag}}
            {{data_form.nama_lengkap}}
        </div>
        <div class="form-group">
            {{data_form.jenis_kelamin.label_tag}}
            {% for component in data_form.jenis_kelamin %}
                <div class="form-check">
                    {{component.tag}}
                    <label for={{component.id_for_label}}>
                        {{component.choice_label}}
                    </label>
                </div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{data_form.tanggal_lahir.label_tag}}
            <div class="form-row">
                {{data_form.tanggal_lahir}}
            </div>
        </div>
        <div class="form-group">
            {{data_form.email.label_tag}}
            {{data_form.email}}
        </div>
        <div class="form-group">
            {{data_form.alamat.label_tag}}
            {{data_form.alamat}}
        </div>
        
        <div class="form-group">
            <div class="form-check">
                {{data_form.agree}}
                <label for={{data_form.agree.id_for_label}}>
                    {{data_form.agree.label}}
                </label>
                {{data_form.agree.choice_label}}
            </div>
        </div>
        

        <button type="submit">Kirim
        </button>
    </form>

{% endblock contents %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}
    {{Content}}

    <h1>{{DetailPost.judul}}</h1>
    <p>{{DetailPost.publish_time}}</p>
    <p>{{DetailPost.body}}</p>
    

{% endblock contents %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}
    {{Content}}

    <br>

        {% for category in Categories %}
            <a href="{% url "blog:category" categoryInput=category.category %}" role="button">{{category.category}}</a>
        {% endfor %}
            <a href="/blog" role="button">All Post</a>

    {% for post in Posts %}
        <a href="{% url "blog:detail" slugInput=post.slug %}">
        <h1>{{post.judul}}</h1>
        </a>
        <p>{{post.publish_time}}</p>
    {% endfor %}
{% endblock contents %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block Title %}

        {% endblock Title %}
    </title>
    
    {% include 'snippets/styles.html' %}
    
</head>
<body>

    {% include 'snippets/navbar.html' %}

    <div class="container mt-3">
        <h1>
            {% block pageTitle %}
            
            {% endblock pageTitle %}
        </h1>

    </div>

    <div class="container mt-4 bg-light shadow">
        {% block contents %}

        {% endblock contents %}

        {% include 'snippets/scripts.html' %}
    </div>
    
</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block contents %}
    {{Content}}
{% endblock contents %}

templates/snippets/navbar.html
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Dinus Repository</a>
            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "index"%}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "blog:index" %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "blog:contact" %}">Kontak</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

templates/snippets/scripts.html
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

templates/snippets/styles.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">